NUMPY

In [ ]:
import numpy as np

In [ ]:
# 1D Array
a = np.array([1,2,3])
print(a)
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)

[1 2 3]
(3,)
1 2 3
[5 2 3]


In [ ]:
# 2D array
b = np.array([[1,2,3],
              [4,5,6]])
print(b)
print(b.shape)
print(b[0,0])

[[1 2 3]
 [4 5 6]]
(2, 3)
1


In [ ]:
#array with zeros
a = np.zeros((2,3))
print(a)
#array with ones
b = np.ones((2,3))
print(b)
#array with any values
c = np.full((2,3), 8)
print(c)
#array with random values
e = np.random.random((3,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[8 8 8]
 [8 8 8]]
[[0.48219695 0.52176687 0.29287603]
 [0.49722995 0.52050005 0.03350555]
 [0.45543387 0.8495519  0.79618283]]


In [ ]:
#array indexing
a = np.array([[0.48219695, 0.52176687, 0.29287603],
              [0.49722995, 0.52050005, 0.03350555],
              [0.45543387, 0.8495519,  0.79618283]])

print(a)

b = a[:2, 1:3]
print(b)
print(a[0,1])
b[0,0] = 10
print(a)

[[0.48219695 0.52176687 0.29287603]
 [0.49722995 0.52050005 0.03350555]
 [0.45543387 0.8495519  0.79618283]]
[[0.52176687 0.29287603]
 [0.52050005 0.03350555]]
0.52176687
[[ 0.48219695 10.          0.29287603]
 [ 0.49722995  0.52050005  0.03350555]
 [ 0.45543387  0.8495519   0.79618283]]


In [ ]:
#boolean indexing
a = np.array([[1,2],
             [3,4],
             [5,6]])

print(a)

print(a>2)

print(a[a>2])

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [ ]:
#basic maths 
x = np.array([[1,2],
             [3,4]])
y = np.array([[5,6],
             [7,8]])
print(np.add(x,y))
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

10
[4 6]
[3 7]
